language: go

os:
  - linux
  - osx

go:
 - 1.11.x

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
 - go build
 - go test -v -coverprofile=coverage.txt -covermode=atomic
 - go test -v -race

after_success:
 - bash <(curl -s https://codecov.io/bash)
