language: go

os:
  - linux
  - osx

go:
 - 1.11.x

script:
 - go build
 - go test -v -coverprofile=coverage.txt -covermode=atomic
 - go test -v -race

after_success:
 - bash <(curl -s https://codecov.io/bash)
